language: php
dist: trusty
php:
  - '7.0'
  - '7.1'
  - nightly
sudo: required
cache:
  directories:
    - $HOME/.composer/cache
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'
before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - composer install --no-interaction --no-scripts --prefer-dist --no-suggest
  - php artisan migrate --force -v
  - php artisan db:seed --force -v
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
notifications:
  email: false
after_success:
  - codecov
